### ISSUE TITLE
Windows Searchbar support

### ISSUE THREAD

**Issue by Z-100** [FlurinBruehwiler/Joa#26]
As a Windows Searchbar user, I want to be able to run "de Joa" on Windows Searchbar.
This includes all Windows Searchbar.
Reaching from Windows to Searchbar.

**Comment by FlurinBruehwilerCMI** [comment]
Custom UI support was dropped.

**Comment by Z-100** [comment]
:( So you stopped with JoaKit? @FlurinBruehwilerCMI

**Comment by FlurinBruehwilerCMI** [comment]
No, you can only use JoaKit, nothing else.
